# Generated by Django 4.0.4 on 2022-05-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='potfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
